// app/layout.js

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LiveBackground from "./components/LiveBackground"; // <-- 1. Import component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LiveBackground /> {/* <-- 2. Thêm component vào đây */}
        {children}
      </body>
    </html>
  );
}